import { AllowedUser, AuditLog, EventItem, NotificationItem, Registration, UserProfile } from '@/types';

export const INITIAL_SUPER_ADMIN_EMAILS = [
  '24f2002110@ds.study.iitm.ac.in',
  '25f2002531@ds.study.iitm.ac.in',
];

export const INITIAL_ALLOWED_USERS: AllowedUser[] = [
  { email: '24f2002110@ds.study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: '25f2002531@ds.study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: 'admin@study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: 'student1@study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: 'student2@study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: 'student3@study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
  { email: 'kaziranga.head@study.iitm.ac.in', importBatchId: 'initial_seed', importedAt: new Date().toISOString() },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'user_super_admin_1',
    email: '24f2002110@ds.study.iitm.ac.in',
    name: 'Amrutanshu Sahoo',
    phone: '+91 9876543210',
    region: 'East',
    level: 'Diploma',
    programme: 'Data Science',
    role: 'SUPER_ADMIN',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    uid: 'user_super_admin_2',
    email: '25f2002531@ds.study.iitm.ac.in',
    name: 'Ananya Sharma',
    phone: '+91 9123456789',
    region: 'South',
    level: 'Degree',
    programme: 'BS Data Science & Applications',
    role: 'SUPER_ADMIN',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    uid: 'user_admin_1',
    email: 'admin@study.iitm.ac.in',
    name: 'Rohan Verma',
    phone: '+91 9988776655',
    region: 'North',
    level: 'Diploma',
    programme: 'Programming',
    role: 'ADMIN',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
  },
  {
    uid: 'user_student_1',
    email: 'student1@study.iitm.ac.in',
    name: 'Priya Sundaram',
    phone: '+91 9445566778',
    region: 'West',
    level: 'Foundation',
    programme: 'BS Electronic Systems',
    role: 'USER',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt_cricket_2026',
    groupId: 'communityDayAug26',
    name: 'Kaziranga Inter-House Cricket Championship 2026',
    description: 'The annual Kaziranga House box cricket showdown! Show off your bowling precision and batting power as Kaziranga takes on rival houses in this high-intensity tournament.',
    category: 'Sports & Fitness',
    startDateTime: new Date(Date.now() + 7 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 8 * 86400000).toISOString(),
    registrationDeadline: new Date(Date.now() + 5 * 86400000).toISOString(),
    venue: 'IIT Madras Sports Ground & Online Virtual Stream',
    registrationType: 'INDIVIDUAL',
    maximumParticipants: 50,
    maximumTeamSize: null,
    rulebookUrl: 'https://example.com/rulebook-cricket.pdf',
    coverImageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    status: 'PUBLISHED',
    createdBy: 'user_super_admin_1',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    currentRegistrationCount: 18,
  },
  {
    id: 'evt_rhino_hackathon',
    groupId: 'communityDayAug26',
    name: 'Rhino Hackathon: AI & Sustainable Tech',
    description: 'A 24-hour rapid prototyping hackathon focusing on AI solutions for environmental sustainability, carbon tracking, and smart house governance. Prizes worth ₹50,000 up for grabs!',
    category: 'Technical & Coding',
    startDateTime: new Date(Date.now() + 14 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 15 * 86400000).toISOString(),
    registrationDeadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    venue: 'Online MS Teams & Kaziranga Innovation Lab',
    registrationType: 'INDIVIDUAL',
    maximumParticipants: 100,
    maximumTeamSize: 4,
    rulebookUrl: 'https://example.com/rulebook-hackathon.pdf',
    coverImageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    status: 'PUBLISHED',
    createdBy: 'user_super_admin_2',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    currentRegistrationCount: 42,
  },
  {
    id: 'evt_cultural_night',
    groupId: 'communityDayAug26',
    name: 'Kaziranga Cultural Night & Drama Showcase',
    description: 'Celebrate our house heritage with vibrant musical performances, theatrical plays, stand-up comedy, and dance battles. Open to all Kaziranga house members.',
    category: 'Cultural & Arts',
    startDateTime: new Date(Date.now() + 21 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() + 21 * 86400000 + 4 * 3600000).toISOString(),
    registrationDeadline: new Date(Date.now() + 18 * 86400000).toISOString(),
    venue: 'Open Air Theatre (OAT) & YouTube Live',
    registrationType: 'INDIVIDUAL',
    maximumParticipants: 200,
    maximumTeamSize: null,
    rulebookUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    status: 'PUBLISHED',
    createdBy: 'user_admin_1',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    currentRegistrationCount: 75,
  },
  {
    id: 'evt_esports_valorant',
    groupId: 'communityDayAug26',
    name: 'Kaziranga E-Sports Valorant Championship',
    description: 'Tactical 5v5 FPS tournament! Clashing for supremacy and house points in the annual Inter-House Gaming League.',
    category: 'Gaming & E-Sports',
    startDateTime: new Date(Date.now() - 2 * 86400000).toISOString(),
    endDateTime: new Date(Date.now() - 1 * 86400000).toISOString(),
    registrationDeadline: new Date(Date.now() - 4 * 86400000).toISOString(),
    venue: 'Discord & Twitch Stream',
    registrationType: 'INDIVIDUAL',
    maximumParticipants: 32,
    maximumTeamSize: 5,
    rulebookUrl: 'https://example.com/valorant-rules.pdf',
    coverImageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    status: 'COMPLETED',
    createdBy: 'user_super_admin_1',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    currentRegistrationCount: 32,
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg_001',
    eventId: 'evt_cricket_2026',
    eventTitle: 'Kaziranga Inter-House Cricket Championship 2026',
    userId: 'user_super_admin_1',
    nameSnapshot: 'Amrutanshu Sahoo',
    emailSnapshot: '24f2002110@ds.study.iitm.ac.in',
    phoneSnapshot: '+91 9876543210',
    regionSnapshot: 'East',
    levelSnapshot: 'Diploma',
    programmeSnapshot: 'Data Science',
    registrationType: 'INDIVIDUAL',
    status: 'CONFIRMED',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'reg_002',
    eventId: 'evt_rhino_hackathon',
    eventTitle: 'Rhino Hackathon: AI & Sustainable Tech',
    userId: 'user_super_admin_2',
    nameSnapshot: 'Ananya Sharma',
    emailSnapshot: '25f2002531@ds.study.iitm.ac.in',
    phoneSnapshot: '+91 9123456789',
    regionSnapshot: 'South',
    levelSnapshot: 'Degree',
    programmeSnapshot: 'BS Data Science & Applications',
    registrationType: 'INDIVIDUAL',
    status: 'CONFIRMED',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'reg_003',
    eventId: 'evt_cultural_night',
    eventTitle: 'Kaziranga Cultural Night & Drama Showcase',
    userId: 'user_student_1',
    nameSnapshot: 'Priya Sundaram',
    emailSnapshot: 'student1@study.iitm.ac.in',
    phoneSnapshot: '+91 9445566778',
    regionSnapshot: 'West',
    levelSnapshot: 'Foundation',
    programmeSnapshot: 'BS Electronic Systems',
    registrationType: 'INDIVIDUAL',
    status: 'CONFIRMED',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'GLOBAL',
    title: 'Welcome to Kaziranga House Portal! 🦏',
    message: 'Discover upcoming inter-house sports, cultural, and tech competitions and secure your house points!',
    type: 'INFO',
    read: false,
    createdAt: new Date().toISOString(),
    isGlobal: true,
  },
  {
    id: 'notif_2',
    userId: 'user_super_admin_1',
    title: 'Registration Confirmed',
    message: 'Your spot in Kaziranga Inter-House Cricket Championship 2026 has been successfully registered.',
    type: 'SUCCESS',
    linkUrl: '/events/evt_cricket_2026',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_001',
    actorUserId: 'user_super_admin_1',
    actorEmail: '24f2002110@ds.study.iitm.ac.in',
    action: 'SYSTEM_BOOTSTRAP',
    target: 'SUPER_ADMIN_ROLES',
    timestamp: new Date(Date.now() - 30 * 86400000).toISOString(),
    metadata: { initialSuperAdmins: INITIAL_SUPER_ADMIN_EMAILS },
  },
  {
    id: 'log_002',
    actorUserId: 'user_super_admin_1',
    actorEmail: '24f2002110@ds.study.iitm.ac.in',
    action: 'ROLE_PROMOTED',
    target: 'user_admin_1 (admin@study.iitm.ac.in)',
    timestamp: new Date(Date.now() - 20 * 86400000).toISOString(),
    metadata: { oldRole: 'USER', newRole: 'ADMIN' },
  },
  {
    id: 'log_003',
    actorUserId: 'user_super_admin_2',
    actorEmail: '25f2002531@ds.study.iitm.ac.in',
    action: 'ALLOWED_USERS_IMPORTED',
    target: 'allowedUsers Collection',
    timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
    metadata: { count: 7, batchId: 'initial_seed' },
  },
];

export const INITIAL_EVENT_GROUPS: import('@/types').EventGroup[] = [
  {
    id: 'communityDayAug26',
    name: "Community Day Aug'26",
    description: 'All activities and events happening on Community Day.',
    coverImageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    status: 'PUBLISHED',
    createdBy: 'user_super_admin_1',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString()
  }
];
